/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

/**
 *
 * @author gbryv
 */
public class VistaVentas extends javax.swing.JFrame {
    // Traemos nuestro gestor para poder consultar los productos
    controlador.GestorInventario gestor = new controlador.GestorInventario();
    
    // Variable para ir sumando el dinero
    double totalVenta = 0.0;
    
    // El modelo para manejar la tabla visualmente
    javax.swing.table.DefaultTableModel modeloCarrito;
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(VistaVentas.class.getName());

    /**
     * Creates new form VistaVentas
     */
    public VistaVentas() {
        initComponents();
        modeloCarrito = (javax.swing.table.DefaultTableModel) tblCarrito.getModel();
        modeloCarrito.setRowCount(0);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lblTotal = new javax.swing.JLabel();
        txtCodigoVenta = new javax.swing.JTextField();
        txtCantidad = new javax.swing.JTextField();
        btnAgregar = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblCarrito = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 0, 0));

        jLabel1.setText("Código del Producto:");

        jLabel2.setText("Cantidad a vender:");

        lblTotal.setText("Total a Pagar: S/ 0.00");

        btnAgregar.setText("Agregar al Carrito");
        btnAgregar.addActionListener(this::btnAgregarActionPerformed);

        jButton2.setText("Procesar Venta");
        jButton2.addActionListener(this::jButton2ActionPerformed);

        tblCarrito.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Código", "Nombre", "Cantidad", "Precio", "Subtotal"
            }
        ));
        jScrollPane1.setViewportView(tblCarrito);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(168, 168, 168)
                .addComponent(btnAgregar)
                .addGap(52, 52, 52)
                .addComponent(jButton2)
                .addGap(0, 260, Short.MAX_VALUE))
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(186, 186, 186)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtCodigoVenta, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(242, 242, 242)
                        .addComponent(lblTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCodigoVenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblTotal)
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAgregar)
                    .addComponent(jButton2))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
        try {
        String codigo = txtCodigoVenta.getText();
        int cantidad = Integer.parseInt(txtCantidad.getText());

        modelo.Producto productoEncontrado = null;
        
        // Buscamos el producto en nuestro inventario usando un foreach
        for (modelo.Producto p : gestor.listar()) {
            if (p.getCodigoBarras().equals(codigo)) {
                productoEncontrado = p;
                break;
            }
        }

        if (productoEncontrado != null) {
            // Verificamos si hay suficiente stock para vender
            if (productoEncontrado.getStock() >= cantidad) {
                
                double subtotal = productoEncontrado.getPrecio() * cantidad;
                
                // Agregamos el producto a la tabla visual (el carrito)
                Object[] fila = {
                    productoEncontrado.getCodigoBarras(),
                    productoEncontrado.getNombre(),
                    cantidad,
                    productoEncontrado.getPrecio(),
                    subtotal
                };
                modeloCarrito.addRow(fila);
                
                // Actualizamos el texto del Total a Pagar en pantalla
                totalVenta += subtotal;
                lblTotal.setText("Total a Pagar: S/ " + String.format("%.2f", totalVenta));
                
                // Limpiamos las cajas para buscar el siguiente producto
                txtCodigoVenta.setText("");
                txtCantidad.setText("");
                
            } else {
                javax.swing.JOptionPane.showMessageDialog(this, "Stock insuficiente. Solo te quedan: " + productoEncontrado.getStock());
            }
        } else {
            javax.swing.JOptionPane.showMessageDialog(this, "El producto no existe en la base de datos.");
        }
    } catch (NumberFormatException e) {
        javax.swing.JOptionPane.showMessageDialog(this, "Por favor, ingresa una cantidad numérica válida.");
    }
    }//GEN-LAST:event_btnAgregarActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // Si la tabla está vacía, no podemos vender
    if (modeloCarrito.getRowCount() == 0) {
        javax.swing.JOptionPane.showMessageDialog(this, "El carrito está vacío.");
        return;
    }

    try (java.sql.Connection con = controlador.ConexionDB.getConexion()) {
        
        // 1. Guardamos el ticket general de la venta
        String sqlVenta = "INSERT INTO ventas (total) VALUES (?)";
        java.sql.PreparedStatement psVenta = con.prepareStatement(sqlVenta, java.sql.Statement.RETURN_GENERATED_KEYS);
        psVenta.setDouble(1, totalVenta);
        psVenta.executeUpdate();
        
        // Obtenemos el número de ticket que nos dio MySQL
        java.sql.ResultSet rs = psVenta.getGeneratedKeys();
        if (rs.next()) {
            int idVenta = rs.getInt(1);
            
            // 2. Recorremos la tabla para guardar los detalles y RESTAR EL STOCK
            for (int i = 0; i < modeloCarrito.getRowCount(); i++) {
                String cod = modeloCarrito.getValueAt(i, 0).toString();
                int cant = Integer.parseInt(modeloCarrito.getValueAt(i, 2).toString());
                double sub = Double.parseDouble(modeloCarrito.getValueAt(i, 4).toString());
                
                // Guardamos el detalle
                String sqlDetalle = "INSERT INTO detalle_ventas (id_venta, codigo_producto, cantidad, subtotal) VALUES (?, ?, ?, ?)";
                java.sql.PreparedStatement psDetalle = con.prepareStatement(sqlDetalle);
                psDetalle.setInt(1, idVenta);
                psDetalle.setString(2, cod);
                psDetalle.setInt(3, cant);
                psDetalle.setDouble(4, sub);
                psDetalle.executeUpdate();
                
                // Buscamos el producto para actualizar su stock
                for (modelo.Producto p : gestor.listar()) {
                    if (p.getCodigoBarras().equals(cod)) {
                        p.actualizarStock(cant); // Resta el stock en la memoria
                        gestor.modificar(p);     // Actualiza el stock en la Base de Datos
                        break;
                    }
                }
            }
            
            javax.swing.JOptionPane.showMessageDialog(this, "¡Venta realizada con éxito! Ticket N° " + idVenta);
            
            // 3. Limpiamos todo para atender al siguiente cliente
            modeloCarrito.setRowCount(0);
            totalVenta = 0.0;
            lblTotal.setText("Total a Pagar: S/ 0.00");
        }
    } catch (java.sql.SQLException e) {
        javax.swing.JOptionPane.showMessageDialog(this, "Error al procesar la venta en BD: " + e.getMessage());
    }
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new VistaVentas().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblTotal;
    private javax.swing.JTable tblCarrito;
    private javax.swing.JTextField txtCantidad;
    private javax.swing.JTextField txtCodigoVenta;
    // End of variables declaration//GEN-END:variables
}
